version: '3.9'

services:
  python_app:
    build: ../etl
    volumes:
      - .:/app
    depends_on:
      - redis
      - elasticsearch
      - postgres
  redis:
    image: redis:7.2.4
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
  db:
    image: postgres:15.0
    env_file:
      - .env
###Вопросы к ревьюеру:
  # 1 - Мой код самый плохочитаемый на потоке?
  # 2 - Правильно ли я применяю принципы ООП? 

  